---
- name: Add grafana apt repository
  apt_repository: repo="deb https://packagecloud.io/grafana/stable/debian/ wheezy main" state=present

- name: Install packagecloud key
  apt_key: url=https://packagecloud.io/gpg.key

- name: Install grafana
  apt: name=grafana state=installed update_cache=true
  notify:
    - Restart grafana

- name: Autostart grafana-server
  service: name=grafana-server enabled=yes
  notify:
    - Restart grafana

- name: Copy grafana config file
  template: src=templates/etc/grafana/grafana.ini.j2 dest=/etc/grafana/grafana.ini
  notify:
    - Restart grafana

- name: Install graphite-carbon
  apt: name=graphite-carbon state=present

- name: Copy carbon config
  template: src=templates/etc/default/graphite-carbon.j2 dest=/etc/default/graphite-carbon
  notify:
    - Restart carbon-cache

- name: Copy carbon storage schema config
  template: src=storage-schemas.conf dest=/etc/carbon/storage-schemas.conf
  notify:
    - Restart carbon-cache

- name: Copy carbon storage aggregation.conf config
  template: src=storage-aggregation.conf dest=/etc/carbon/storage-aggregation.conf
  notify:
    - Restart carbon-cache

- name: Copy main carbon config
  template: src=carbon.conf dest=/etc/carbon/carbon.conf
  notify:
    - Restart carbon-cache

- name: Install graphite-web
  apt: name=graphite-web state=present

- name: Install graphite-carbon
  apt: name=graphite-carbon state=present

- name: Install uwsgi-plugin-python
  apt: name=uwsgi-plugin-python state=present

- name: Install uwsgi
  apt: name=uwsgi state=present

- name: Copy uwsgi config
  template: src=templates/etc/uwsgi/apps-available/graphite.ini.j2 dest=/etc/uwsgi/apps-available/graphite.ini
  notify: Restart uwsgi

- name: Activate graphite config
  file: src=/etc/uwsgi/apps-available/graphite.ini dest=/etc/uwsgi/apps-enabled/graphite.ini state=link
  notify: Restart uwsgi

- name: Autostart uwsgi
  service: name=uwsgi enabled=yes
  notify: Restart uwsgi

- name: Create graphite log dir
  file: path=/var/log/graphite state=directory mode=0755 owner=_graphite group=_graphite

- name: Sync carbon database
  command: graphite-manage syncdb --noinput creates=/var/lib/graphite/graphite.db

- name: Adjust carbon database permissions
  file: path=/var/lib/graphite/graphite.db owner=_graphite group=_graphite
  notify: Restart uwsgi

- name: Adjust graphite search index permissions
  file: path=/var/lib/graphite/search_index group=www-data state=touch
  notify: Restart uwsgi

- name: Add www-data to _graphite group
  user: name=www-data groups=_graphite append=yes

- name: Run all pending handlers, since other roles depend on services to be running
  meta: flush_handlers
