---
- name: Copy credentials file
  template: src=credentials.xml dest=/var/lib/jenkins/credentials.xml owner=jenkins group=jenkins
  register: jenkins_credentials_file

- name: Ensure URL prefix is present in Jenkins config
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^JENKINS_ARGS='
    line: 'JENKINS_ARGS="$JENKINS_ARGS --prefix={{ jenkins_url_prefix }}"'
    state: present
  register: jenkins_init_prefix

- name: Set HTTP port in Jenkins config
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Immediately restart Jenkins on config changes
  service: name=jenkins state=restarted
  when: (jenkins_credentials_file.changed or jenkins_init_prefix.changed or jenkins_http_config.changed)
