---
- name: Update all packages to the latest version
  apt: upgrade=dist

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: Make sure unattended-upgrades only installs from ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

- name: Prevent ssh daemon from accepting locale variables
  lineinfile: dest=/etc/ssh/sshd_config regexp="AcceptEnv" state=absent
  register: sshd_config

- name: Immediately restart ssh daemon on config changes
  service: name=ssh state=restarted
  when: sshd_config.changed

- name: Install htop
  action: apt pkg=htop state=present

- name: Install ntp
  action: apt pkg=ntp state=present
