---
- name: install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: make sure unattended-upgrades only installs from ubuntu_release-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
