---
- name: Set timezone to London
  file: src=/usr/share/zoneinfo/Europe/London dest=/etc/localtime owner=root group=root mode=0644 state=link
  register: timezone

- name: Update timezone immediately if changed
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: timezone.changed
